"use client";

import React, { useState, useEffect } from "react";
import { useApp } from "../../context/AppContext";
import { PRODUCTS_DATA } from "../../data/products";
import { supabase, hasValidSupabaseConfig } from "../../lib/supabase";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  DatabaseIcon,
  CheckmarkCircle02Icon,
  AlertCircleIcon,
  Copy01Icon,
  RefreshIcon,
  Database01Icon,
  ArrowRight01Icon,
  TickDouble01Icon
} from "@hugeicons/core-free-icons";

export default function DatabaseConsolePage() {
  const { products, productsLoading, isDbConnected, refreshProducts } = useApp();
  const [checking, setChecking] = useState(false);
  const [dbProductCount, setDbProductCount] = useState<number | null>(null);
  const [tableExists, setTableExists] = useState<boolean | null>(null);
  const [syncing, setSyncing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [syncLog, setSyncLog] = useState<string[]>([]);

  const sqlSchema = `-- 1. Create the products table with camelCase columns to match TypeScript
CREATE TABLE public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  "skinType" TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  price INTEGER NOT NULL,
  "originalPrice" INTEGER NOT NULL,
  discount INTEGER DEFAULT 0,
  "imageColor" TEXT DEFAULT 'from-zinc-100 to-zinc-200',
  "imageUrl" TEXT,
  "isBogo" BOOLEAN DEFAULT false,
  "bogoLabel" TEXT,
  "isFlashSale" BOOLEAN DEFAULT false,
  "isFlatPercentage" BOOLEAN DEFAULT false
);

-- 2. Create the orders table to track checkouts
CREATE TABLE public.orders (
  id TEXT PRIMARY KEY,
  customer TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  date TEXT NOT NULL,
  items JSONB NOT NULL,
  shipping INTEGER DEFAULT 80,
  status TEXT DEFAULT 'Pending'
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 4. Create policies for products
CREATE POLICY "Allow public read products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public insert products" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update products" ON public.products FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete products" ON public.products FOR DELETE USING (true);

-- 5. Create policies for orders
CREATE POLICY "Allow public read orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update orders" ON public.orders FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete orders" ON public.orders FOR DELETE USING (true);

-- 6. Create the coupons table
CREATE TABLE public.coupons (
  code TEXT PRIMARY KEY,
  discount INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  expiry TEXT NOT NULL
);

-- 7. Create the campaign settings table
CREATE TABLE public.campaign_settings (
  id TEXT PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'Running',
  "countdownDate" TEXT NOT NULL
);

-- 8. Enable Row Level Security (RLS)
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_settings ENABLE ROW LEVEL SECURITY;

-- 9. Create policies for coupons
CREATE POLICY "Allow public read coupons" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "Allow public insert coupons" ON public.coupons FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update coupons" ON public.coupons FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete coupons" ON public.coupons FOR DELETE USING (true);

-- 10. Create policies for campaign_settings
CREATE POLICY "Allow public read campaign_settings" ON public.campaign_settings FOR SELECT USING (true);
CREATE POLICY "Allow public insert campaign_settings" ON public.campaign_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update campaign_settings" ON public.campaign_settings FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete campaign_settings" ON public.campaign_settings FOR DELETE USING (true);

-- 11. Seed initial data
INSERT INTO public.campaign_settings (id, status, "countdownDate") 
VALUES ('boishakhi', 'Running', '2026-06-15T23:59:59')
ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.coupons (code, discount, status, expiry)
VALUES 
  ('BOOTH15', 15, 'Active', '2026-05-31'),
  ('BOISHAKHI25', 25, 'Active', '2026-06-15'),
  ('GLOW10', 10, 'Active', '2026-05-28'),
  ('EID30', 30, 'Expired', '2026-04-12')
ON CONFLICT (code) DO NOTHING;

-- 12. Create Supabase Storage Bucket ('products') & policies
-- Run this in your Supabase SQL editor to enable file uploads!
INSERT INTO storage.buckets (id, name, public) 
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access Objects" ON storage.objects FOR SELECT USING (bucket_id = 'products');
CREATE POLICY "Public Insert Objects" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'products');
CREATE POLICY "Public Update Objects" ON storage.objects FOR UPDATE USING (bucket_id = 'products') WITH CHECK (bucket_id = 'products');
CREATE POLICY "Public Delete Objects" ON storage.objects FOR DELETE USING (bucket_id = 'products');

-- 13. Create profiles table linked to Supabase Auth users
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  name TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  zip TEXT,
  avatar TEXT
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow individual update profiles" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Create trigger function to automatically assign admin role on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, name, phone)
  VALUES (
    new.id, 
    new.email, 
    CASE WHEN new.email = 'admin@glowmarketbd.com' THEN 'admin' ELSE 'user' END,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'phone', '')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger to auth.users table
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Seed profile for existing admin users (if any exist)
INSERT INTO public.profiles (id, email, role)
SELECT id, email, 'admin'
FROM auth.users
WHERE email = 'admin@glowmarketbd.com'
ON CONFLICT (id) DO NOTHING;`;

  const verifyConnection = async () => {
    if (!hasValidSupabaseConfig) {
      setTableExists(false);
      setDbProductCount(null);
      return;
    }

    setChecking(true);
    try {
      // Test querying the products table
      const { count, error: productsError } = await supabase
        .from("products")
        .select("id", { count: "exact", head: true });

      // Test querying the orders table
      const { error: ordersError } = await supabase
        .from("orders")
        .select("id")
        .limit(1);

      if (productsError) {
        if (productsError.code === "PGRST205" || productsError.message?.includes("does not exist")) {
          setTableExists(false);
          setDbProductCount(null);
          setSyncLog(prev => [...prev, "❌ Table public.products not found in schema cache."]);
          return;
        } else {
          throw productsError;
        }
      }

      if (ordersError) {
        if (ordersError.code === "PGRST205" || ordersError.message?.includes("does not exist")) {
          setTableExists(false);
          setDbProductCount(count ?? 0);
          setSyncLog(prev => [...prev, "❌ Table public.orders not found in schema cache."]);
          return;
        } else {
          throw ordersError;
        }
      }

      setTableExists(true);
      setDbProductCount(count ?? 0);
      setSyncLog(prev => [...prev, `✅ Connected! Table public.products (${count ?? 0} items) and public.orders both exist.`]);
    } catch (err: any) {
      console.error("Database check error:", err);
      setTableExists(false);
      setDbProductCount(null);
      setSyncLog(prev => [...prev, `❌ Connection error: ${err.message || err}`]);
    } finally {
      setChecking(false);
    }
  };

  useEffect(() => {
    verifyConnection();
  }, [isDbConnected]);

  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSyncData = async () => {
    if (syncing || !tableExists) return;

    if (
      dbProductCount &&
      dbProductCount > 0 &&
      !confirm("Warning: Database already contains products. Syncing will insert/overwrite items. Continue?")
    ) {
      return;
    }

    setSyncing(true);
    setSyncLog(prev => [...prev, "🔄 Starting data synchronization to Supabase..."]);

    try {
      // Clean up mock data to insert into db
      const dataToInsert = PRODUCTS_DATA.map(p => ({
        id: p.id,
        brand: p.brand,
        name: p.name,
        category: p.category,
        skinType: p.skinType,
        rating: p.rating,
        price: p.price,
        originalPrice: p.originalPrice,
        discount: p.discount,
        imageColor: p.imageColor,
        imageUrl: p.imageUrl,
        isBogo: p.isBogo,
        bogoLabel: p.bogoLabel || null,
        isFlashSale: p.isFlashSale,
        isFlatPercentage: p.isFlatPercentage
      }));

      // In Supabase, upsert allows replacing records if primary key conflicts
      const { data, error } = await supabase
        .from("products")
        .upsert(dataToInsert, { onConflict: "id" });

      if (error) throw error;

      setSyncLog(prev => [...prev, `🎉 Successfully synced ${PRODUCTS_DATA.length} products to Supabase!`]);
      await verifyConnection();
      await refreshProducts();
    } catch (err: any) {
      console.error("Sync error:", err);
      setSyncLog(prev => [...prev, `❌ Sync failed: ${err.message || err}`]);
    } finally {
      setSyncing(false);
    }
  };

  return (
    <div className="flex flex-col gap-8">
      {/* 1. Header Hero */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-3xl font-black text-zinc-900 tracking-tight">Database Settings</h1>
          <p className="text-sm text-zinc-400 font-semibold leading-relaxed">
            Manage your Supabase database integration, schema verification, and mock data synchronization.
          </p>
        </div>
        <button
          onClick={verifyConnection}
          disabled={checking}
          className="bg-zinc-900 hover:bg-zinc-800 disabled:opacity-50 text-white text-xs font-black uppercase px-5 py-3 rounded-2xl transition-all cursor-pointer flex items-center gap-2"
        >
          <HugeiconsIcon icon={RefreshIcon} size={14} className={checking ? "animate-spin" : ""} />
          <span>{checking ? "Pinging..." : "Check Connection"}</span>
        </button>
      </div>

      {/* 2. Overview Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Connection Status Card */}
        <div className="bg-white border border-zinc-100 rounded-3xl p-6 flex flex-col justify-between shadow-xs">
          <div className="flex flex-col gap-1.5">
            <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Supabase Config</span>
            {hasValidSupabaseConfig ? (
              <div className="flex items-center gap-2 mt-2">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-lg font-black text-emerald-600">Keys Initialized</span>
              </div>
            ) : (
              <div className="flex items-center gap-2 mt-2">
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500" />
                <span className="text-lg font-black text-amber-600">Config Missing</span>
              </div>
            )}
            <p className="text-xs font-semibold text-zinc-400 mt-2 leading-relaxed">
              Status of your <code>.env</code> credentials in the application workspace.
            </p>
          </div>
        </div>

        {/* Database Table Status Card */}
        <div className="bg-white border border-zinc-100 rounded-3xl p-6 flex flex-col justify-between shadow-xs">
          <div className="flex flex-col gap-1.5">
            <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Table Schema Cache</span>
            {tableExists === true ? (
              <div className="flex items-center gap-2 mt-2">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
                <span className="text-lg font-black text-emerald-600">Active (products)</span>
              </div>
            ) : tableExists === false ? (
              <div className="flex items-center gap-2 mt-2">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500 animate-pulse" />
                <span className="text-lg font-black text-rose-600">Missing Table</span>
              </div>
            ) : (
              <div className="flex items-center gap-2 mt-2">
                <span className="w-2.5 h-2.5 rounded-full bg-zinc-300 animate-pulse" />
                <span className="text-lg font-black text-zinc-400">Verifying...</span>
              </div>
            )}
            <p className="text-xs font-semibold text-zinc-400 mt-2 leading-relaxed">
              Check if the <code>public.products</code> table has been created on your Supabase project.
            </p>
          </div>
        </div>

        {/* Sync Status Card */}
        <div className="bg-white border border-zinc-100 rounded-3xl p-6 flex flex-col justify-between shadow-xs">
          <div className="flex flex-col gap-1.5">
            <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Database Record Count</span>
            <div className="text-2xl font-black text-zinc-900 mt-1">
              {dbProductCount !== null ? `${dbProductCount} Products` : "0 (Mock Fallback)"}
            </div>
            <p className="text-xs font-semibold text-zinc-400 mt-2 leading-relaxed">
              Number of live items currently indexed inside the Supabase tables.
            </p>
          </div>
        </div>
      </div>

      {/* 3. Columns */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Left Column: Schema SQL Helper */}
        <div className="bg-white border border-zinc-100 rounded-3xl p-6 flex flex-col gap-6 shadow-xs">
          <div className="flex items-center justify-between border-b border-zinc-50 pb-4">
            <div className="flex items-center gap-2.5">
              <HugeiconsIcon icon={DatabaseIcon} className="text-[#FF1A58]" size={20} />
              <span className="font-extrabold text-base text-zinc-900">Database Schema Setup</span>
            </div>
            <button
              onClick={handleCopySql}
              className="text-xs font-bold text-[#FF1A58] hover:underline flex items-center gap-1 cursor-pointer"
            >
              <HugeiconsIcon icon={copied ? TickDouble01Icon : Copy01Icon} size={14} />
              <span>{copied ? "Copied SQL!" : "Copy SQL"}</span>
            </button>
          </div>

          <div className="flex flex-col gap-4">
            <div className="bg-amber-50 border border-amber-200/50 rounded-2xl p-4 flex gap-3 text-amber-800 text-xs font-semibold leading-relaxed">
              <HugeiconsIcon icon={AlertCircleIcon} className="shrink-0 text-amber-600 mt-0.5" size={16} />
              <div>
                If your table is missing, log into your{" "}
                <a
                  href="https://supabase.com/dashboard"
                  target="_blank"
                  rel="noreferrer"
                  className="underline font-bold"
                >
                  Supabase Dashboard
                </a>
                , open the <strong>SQL Editor</strong>, paste the schema script below, and hit <strong>Run</strong>.
              </div>
            </div>

            <div className="bg-zinc-950 text-zinc-300 rounded-2xl p-4 font-mono text-[10.5px] leading-relaxed max-h-72 overflow-y-auto border border-zinc-900 select-text">
              <pre className="whitespace-pre-wrap">{sqlSchema}</pre>
            </div>
          </div>
        </div>

        {/* Right Column: Sync Console & Operations */}
        <div className="flex flex-col gap-8">
          {/* Sync Card */}
          <div className="bg-white border border-zinc-100 rounded-3xl p-6 flex flex-col gap-6 shadow-xs">
            <span className="font-extrabold text-base text-zinc-900 border-b border-zinc-50 pb-4">
              Data Synchronization
            </span>

            <p className="text-xs font-semibold text-zinc-400 leading-relaxed">
              Once you create the table schema in Supabase, click below to automatically populate the database
              with the 31 high-fidelity mock products from the local file system catalog.
            </p>

            <button
              onClick={handleSyncData}
              disabled={syncing || !tableExists}
              className={`w-full py-4.5 rounded-2xl font-black text-xs uppercase transition-all tracking-wider cursor-pointer flex items-center justify-center gap-2 ${
                tableExists
                  ? "bg-[#FF1A58] hover:bg-[#e11d48] text-white shadow-lg shadow-[#FF1A58]/20"
                  : "bg-zinc-100 text-zinc-400 cursor-not-allowed border border-zinc-200/50"
              }`}
            >
              <HugeiconsIcon icon={Database01Icon} size={16} className={syncing ? "animate-spin" : ""} />
              <span>{syncing ? "Syncing products..." : "Sync Mock Data to Supabase"}</span>
            </button>
            
            {!tableExists && (
              <span className="text-[10px] text-center font-bold text-rose-500 -mt-2">
                ⚠️ Create the SQL table schema in Supabase before syncing data.
              </span>
            )}
          </div>

          {/* Sync Live Console Logging */}
          <div className="bg-white border border-zinc-100 rounded-3xl p-6 flex flex-col gap-4 shadow-xs flex-1 min-h-[220px]">
            <span className="font-extrabold text-xs text-zinc-400 uppercase tracking-widest">
              Live Connection Logs
            </span>
            <div className="bg-zinc-50 border border-zinc-100 rounded-2xl p-4 flex-1 font-mono text-[11px] leading-relaxed text-zinc-600 select-text overflow-y-auto max-h-56">
              {syncLog.length === 0 ? (
                <span className="text-zinc-400 italic">No logs recorded yet. Verify connection.</span>
              ) : (
                <div className="flex flex-col gap-1.5">
                  {syncLog.map((log, idx) => (
                    <div key={idx}>{log}</div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
